// flow-typed signature: dd6cc9595261dadab5f680475ec3b8d4
// flow-typed version: <<STUB>>/codesandbox_v^1.1.14/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'codesandbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'codesandbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'codesandbox/lib/api/define' {
  declare module.exports: any;
}

declare module 'codesandbox/lib/cfg' {
  declare module.exports: any;
}

declare module 'codesandbox/lib/commands/deploy' {
  declare module.exports: any;
}

declare module 'codesandbox/lib/commands/login' {
  declare module.exports: any;
}

declare module 'codesandbox/lib/commands/logout' {
  declare module.exports: any;
}

declare module 'codesandbox/lib/github/url' {
  declare module.exports: any;
}

declare module 'codesandbox/lib/index' {
  declare module.exports: any;
}

declare module 'codesandbox/lib/utils/api' {
  declare module.exports: any;
}

declare module 'codesandbox/lib/utils/confirm' {
  declare module.exports: any;
}

declare module 'codesandbox/lib/utils/log' {
  declare module.exports: any;
}

declare module 'codesandbox/lib/utils/parse-sandbox/file-error' {
  declare module.exports: any;
}

declare module 'codesandbox/lib/utils/parse-sandbox/index' {
  declare module.exports: any;
}

declare module 'codesandbox/lib/utils/url' {
  declare module.exports: any;
}

// Filename aliases
declare module 'codesandbox/lib/api/define.js' {
  declare module.exports: $Exports<'codesandbox/lib/api/define'>;
}
declare module 'codesandbox/lib/cfg.js' {
  declare module.exports: $Exports<'codesandbox/lib/cfg'>;
}
declare module 'codesandbox/lib/commands/deploy.js' {
  declare module.exports: $Exports<'codesandbox/lib/commands/deploy'>;
}
declare module 'codesandbox/lib/commands/login.js' {
  declare module.exports: $Exports<'codesandbox/lib/commands/login'>;
}
declare module 'codesandbox/lib/commands/logout.js' {
  declare module.exports: $Exports<'codesandbox/lib/commands/logout'>;
}
declare module 'codesandbox/lib/github/url.js' {
  declare module.exports: $Exports<'codesandbox/lib/github/url'>;
}
declare module 'codesandbox/lib/index.js' {
  declare module.exports: $Exports<'codesandbox/lib/index'>;
}
declare module 'codesandbox/lib/utils/api.js' {
  declare module.exports: $Exports<'codesandbox/lib/utils/api'>;
}
declare module 'codesandbox/lib/utils/confirm.js' {
  declare module.exports: $Exports<'codesandbox/lib/utils/confirm'>;
}
declare module 'codesandbox/lib/utils/log.js' {
  declare module.exports: $Exports<'codesandbox/lib/utils/log'>;
}
declare module 'codesandbox/lib/utils/parse-sandbox/file-error.js' {
  declare module.exports: $Exports<'codesandbox/lib/utils/parse-sandbox/file-error'>;
}
declare module 'codesandbox/lib/utils/parse-sandbox/index.js' {
  declare module.exports: $Exports<'codesandbox/lib/utils/parse-sandbox/index'>;
}
declare module 'codesandbox/lib/utils/url.js' {
  declare module.exports: $Exports<'codesandbox/lib/utils/url'>;
}
