// flow-typed signature: c8a67a60c42c42d2914cc997a11e10c8
// flow-typed version: <<STUB>>/gh-pages_v^1.1.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gh-pages'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gh-pages' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gh-pages/lib/git' {
  declare module.exports: any;
}

declare module 'gh-pages/lib/index' {
  declare module.exports: any;
}

declare module 'gh-pages/lib/util' {
  declare module.exports: any;
}

declare module 'gh-pages/plugin' {
  declare module.exports: any;
}

declare module 'gh-pages/test/bin/gh-pages.spec' {
  declare module.exports: any;
}

declare module 'gh-pages/test/helper' {
  declare module.exports: any;
}

declare module 'gh-pages/test/integration/basic.spec' {
  declare module.exports: any;
}

declare module 'gh-pages/test/integration/dest.spec' {
  declare module.exports: any;
}

declare module 'gh-pages/test/integration/fixtures/include/expected/good' {
  declare module.exports: any;
}

declare module 'gh-pages/test/integration/fixtures/include/local/good' {
  declare module.exports: any;
}

declare module 'gh-pages/test/integration/include.spec' {
  declare module.exports: any;
}

declare module 'gh-pages/test/lib/util.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gh-pages/lib/git.js' {
  declare module.exports: $Exports<'gh-pages/lib/git'>;
}
declare module 'gh-pages/lib/index.js' {
  declare module.exports: $Exports<'gh-pages/lib/index'>;
}
declare module 'gh-pages/lib/util.js' {
  declare module.exports: $Exports<'gh-pages/lib/util'>;
}
declare module 'gh-pages/plugin.js' {
  declare module.exports: $Exports<'gh-pages/plugin'>;
}
declare module 'gh-pages/test/bin/gh-pages.spec.js' {
  declare module.exports: $Exports<'gh-pages/test/bin/gh-pages.spec'>;
}
declare module 'gh-pages/test/helper.js' {
  declare module.exports: $Exports<'gh-pages/test/helper'>;
}
declare module 'gh-pages/test/integration/basic.spec.js' {
  declare module.exports: $Exports<'gh-pages/test/integration/basic.spec'>;
}
declare module 'gh-pages/test/integration/dest.spec.js' {
  declare module.exports: $Exports<'gh-pages/test/integration/dest.spec'>;
}
declare module 'gh-pages/test/integration/fixtures/include/expected/good.js' {
  declare module.exports: $Exports<'gh-pages/test/integration/fixtures/include/expected/good'>;
}
declare module 'gh-pages/test/integration/fixtures/include/local/good.js' {
  declare module.exports: $Exports<'gh-pages/test/integration/fixtures/include/local/good'>;
}
declare module 'gh-pages/test/integration/include.spec.js' {
  declare module.exports: $Exports<'gh-pages/test/integration/include.spec'>;
}
declare module 'gh-pages/test/lib/util.spec.js' {
  declare module.exports: $Exports<'gh-pages/test/lib/util.spec'>;
}
