// flow-typed signature: d9c864251453e982016d4a523a240675
// flow-typed version: <<STUB>>/react-sortable-tree-theme-file-explorer_v^1.1.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sortable-tree-theme-file-explorer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sortable-tree-theme-file-explorer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sortable-tree-theme-file-explorer/dist/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sortable-tree-theme-file-explorer/dist/main.js' {
  declare module.exports: $Exports<'react-sortable-tree-theme-file-explorer/dist/main'>;
}
