// flow-typed signature: 4561b361b2311de3bd260ef8ee05f919
// flow-typed version: <<STUB>>/react-dnd-test-backend_v^2.5.4/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dnd-test-backend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dnd-test-backend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dnd-test-backend/lib/index' {
  declare module.exports: any;
}

declare module 'react-dnd-test-backend/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dnd-test-backend/lib/index.js' {
  declare module.exports: $Exports<'react-dnd-test-backend/lib/index'>;
}
declare module 'react-dnd-test-backend/src/index.js' {
  declare module.exports: $Exports<'react-dnd-test-backend/src/index'>;
}
