// flow-typed signature: 93942e853693bd31777f63e394bc4218
// flow-typed version: <<STUB>>/react-dnd-scrollzone_v^4.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dnd-scrollzone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dnd-scrollzone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dnd-scrollzone/lib/index' {
  declare module.exports: any;
}

declare module 'react-dnd-scrollzone/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dnd-scrollzone/lib/index.js' {
  declare module.exports: $Exports<'react-dnd-scrollzone/lib/index'>;
}
declare module 'react-dnd-scrollzone/lib/util.js' {
  declare module.exports: $Exports<'react-dnd-scrollzone/lib/util'>;
}
