// flow-typed signature: cd574ee73af3fa79f67205821f8db331
// flow-typed version: <<STUB>>/react-dnd-touch-backend_v^0.3.20/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dnd-touch-backend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dnd-touch-backend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dnd-touch-backend/dist/Touch.browserified' {
  declare module.exports: any;
}

declare module 'react-dnd-touch-backend/dist/Touch' {
  declare module.exports: any;
}

declare module 'react-dnd-touch-backend/src/Touch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dnd-touch-backend/dist/Touch.browserified.js' {
  declare module.exports: $Exports<'react-dnd-touch-backend/dist/Touch.browserified'>;
}
declare module 'react-dnd-touch-backend/dist/Touch.js' {
  declare module.exports: $Exports<'react-dnd-touch-backend/dist/Touch'>;
}
declare module 'react-dnd-touch-backend/src/Touch.js' {
  declare module.exports: $Exports<'react-dnd-touch-backend/src/Touch'>;
}
