// flow-typed signature: ab0e8bd6fb843c46336210075ef67400
// flow-typed version: <<STUB>>/@storybook/addon-options_v^3.3.12/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-options'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-options' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-options/dist/manager/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-options/dist/preview/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-options/dist/shared/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-options/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-options/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-options/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-options/src/manager/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-options/src/preview/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-options/src/shared/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-options/dist/manager/index.js' {
  declare module.exports: $Exports<'@storybook/addon-options/dist/manager/index'>;
}
declare module '@storybook/addon-options/dist/preview/index.js' {
  declare module.exports: $Exports<'@storybook/addon-options/dist/preview/index'>;
}
declare module '@storybook/addon-options/dist/shared/index.js' {
  declare module.exports: $Exports<'@storybook/addon-options/dist/shared/index'>;
}
declare module '@storybook/addon-options/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-options/manager'>;
}
declare module '@storybook/addon-options/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-options/preview'>;
}
declare module '@storybook/addon-options/register.js' {
  declare module.exports: $Exports<'@storybook/addon-options/register'>;
}
declare module '@storybook/addon-options/src/manager/index.js' {
  declare module.exports: $Exports<'@storybook/addon-options/src/manager/index'>;
}
declare module '@storybook/addon-options/src/preview/index.js' {
  declare module.exports: $Exports<'@storybook/addon-options/src/preview/index'>;
}
declare module '@storybook/addon-options/src/shared/index.js' {
  declare module.exports: $Exports<'@storybook/addon-options/src/shared/index'>;
}
